title: Pradeep Kumar D S
logo: /assets/img/amb_spiceestew_2.png
description: Researcher • Philosopher • Scholar • Scientist • [LinkedIn](https://www.linkedin.com/in/dspradeep/)
show_downloads: false
google_analytics: G-C4SQVZ29G7
theme: jekyll-theme-minimal


