title: Pradeep Kumar D S
logo: /assets/img/amb_spiceestew_2.png
description: Researcher • Philosopher • Scholar • Scientist
description: + [Google Scholar](https://scholar.google.com/citations?hl=en&user=XwFbfMMAAAAJ)
+ [ORCID](https://orcid.org/0000-0002-1085-4005)
+ [LinkedIn](https://www.linkedin.com/in/dspradeep/)
show_downloads: false
google_analytics: G-C4SQVZ29G7
theme: jekyll-theme-minimal


